[package]
name = "xmrs"
version = "0.3.4"
edition = "2021"
description = "A library to edit SoundTracker data with pleasure "
license = "MIT"
authors = ["Sebastien Bechet"]
documentation = "https://docs.rs/xmrs"
repository = "https://github.com/sbechet/xmrs"
readme = "README.md"

keywords = ["xm", "module", "mod", "s3m", "tracker"]
categories = ["multimedia::audio"]

[dependencies]
bincode = "1.3"
libflate = "2.0"
num_enum = "0.7"
rand = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }
serde-big-array = "0.5"

[lib]
name = "xmrs"
path = "src/lib.rs"

[[bin]]
name = "xmrs"
path = "src/bin/xmrs.rs"
