[package]
name = "xmrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
num_enum = "0.5.11"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.0"

[lib]
name = "xmrs"
path = "src/lib.rs"

[[bin]]
name = "xmrs"
path = "src/bin/xmrs.rs"
