[package]
name = "xmrs"
version = "0.2.5"
edition = "2021"
description = "XMrs is Safe a SoundTracker Library"
license = "MIT"
authors = ["Sebastien Bechet"]
documentation = "https://docs.rs/xmrs"
repository = "https://github.com/sbechet/xmrs"
readme = "README.md"

keywords = ["soundtracker", "demo", "scene", "xm", "module", "mod", "s3m", "fasttracker", "protracker", "tracker"]
categories = ["music", "audio"]

[dependencies]
bincode = "1.3"
libflate = "1.3"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5"

[lib]
name = "xmrs"
path = "src/lib.rs"

[[bin]]
name = "xmrs"
path = "src/bin/xmrs.rs"
