[package]
name = "xmrs"
version = "0.6.0"
edition = "2021"
description = "A library to edit SoundTracker data with pleasure "
license = "MIT"
authors = ["Sebastien Bechet"]
documentation = "https://docs.rs/xmrs"
repository = "https://codeberg.org/sbechet/xmrs"
readme = "README.md"

keywords = ["xm", "module", "mod", "s3m", "tracker"]
categories = ["multimedia::audio", "embedded", "no-std"]

[dependencies]
bincode = "1.3"
clap = { version = "4.5", optional = true, features = ["cargo", "derive"] }
num_enum = "0.7"
serde = { version = "1.0", features = ["derive", "alloc"] }
serde-big-array = "0.5"

[features]
default = []
demo = ["clap"]

[lib]
name = "xmrs"
path = "src/lib.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

