[package]
name = "xmrs"
version = "0.2.2"
edition = "2021"
description = "XMrs is Safe a SoundTracker Library"
license = "MIT"
authors = ["Sebastien Bechet"]

[dependencies]
bincode = "1.3"
core2 = "0.4"
libflate = "1.3"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5"

[lib]
name = "xmrs"
path = "src/lib.rs"

[[bin]]
name = "xmrs"
path = "src/bin/xmrs.rs"
