[package]
name = "xmrs"
version = "0.1.0"
edition = "2021"
description = "XM FastTracker II library in full rust"
license = "MIT"
authors = ["Sebastien Bechet"]

[dependencies]
bincode = "1.3.3"
core2 = "0.4.0"
libflate = "1.3.0"
num_enum = "0.5.11"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.0"

[lib]
name = "xmrs"
path = "src/lib.rs"

[[bin]]
name = "xmrs"
path = "src/bin/xmrs.rs"
